name: provider_assignment
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Compatible with Flutter 3.x

flutter:
  uses-material-design: true

  # Uncomment below to add assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
